### Pandas
1. Pandas DataFrame
2. Pandas Series
3. Pandas Basic Operation

In [1]:
!pip install pandas

In [2]:
import pandas as pd
import numpy as np

In [3]:
np.arange(0,20).reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [4]:
## create a DataFrame
df=pd.DataFrame(data=np.arange(0,20).reshape(5,4),index=["Row1","Row2","Row3","Row4","Row5"],
             columns=["Column1","Column2","Column3","Column4"])

In [5]:
type(df)

pandas.core.frame.DataFrame

In [6]:
df.head(2)

Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row2        4        5        6        7

In [7]:
df.tail(3)

Column1  Column2  Column3  Column4
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19

In [8]:
df.describe()

Column1    Column2    Column3    Column4
count   5.000000   5.000000   5.000000   5.000000
mean    8.000000   9.000000  10.000000  11.000000
std     6.324555   6.324555   6.324555   6.324555
min     0.000000   1.000000   2.000000   3.000000
25%     4.000000   5.000000   6.000000   7.000000
50%     8.000000   9.000000  10.000000  11.000000
75%    12.000000  13.000000  14.000000  15.000000
max    16.000000  17.000000  18.000000  19.000000

In [9]:
df.head()

Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19

In [10]:
df[['Column1','Column2','Column3']]

Column1  Column2  Column3
Row1        0        1        2
Row2        4        5        6
Row3        8        9       10
Row4       12       13       14
Row5       16       17       18

In [11]:
type(df[['Column1']])

pandas.core.frame.DataFrame

In [12]:
type(df['Column1'])

pandas.core.series.Series

In [13]:
df

Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19

In [14]:
df.loc[["Row1","Row3"]]

Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row3        8        9       10       11

In [15]:
df

Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19

In [16]:
df.iloc[0:3,0:2]

Column1  Column2
Row1        0        1
Row2        4        5
Row3        8        9

In [17]:
df.iloc[2:4,1:3].values

array([[ 9, 10],
       [13, 14]])

In [18]:
np.nan

nan

In [19]:
df=pd.DataFrame(data=[[1,np.nan,2],[1,3,4],[5,4,3]],index=["Row1",
                                                      "Row2","Row3"],columns=["Column1",
                                                                             "Column2",
                                                                             "Column3",
                                                                             ])
df

Column1  Column2  Column3
Row1        1      NaN        2
Row2        1      3.0        4
Row3        5      4.0        3

In [20]:
df.isnull()

Column1  Column2  Column3
Row1    False     True    False
Row2    False    False    False
Row3    False    False    False

In [21]:
df.isnull().sum()

Column1    0
Column2    1
Column3    0
dtype: int64

In [22]:
df.isna().sum()

Column1    0
Column2    1
Column3    0
dtype: int64

In [23]:
df

Column1  Column2  Column3
Row1        1      NaN        2
Row2        1      3.0        4
Row3        5      4.0        3

In [24]:
type(np.nan)

float

In [25]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3 entries, Row1 to Row3
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   Column1  3 non-null      int64  
 1   Column2  2 non-null      float64
 2   Column3  3 non-null      int64  
dtypes: float64(1), int64(2)
memory usage: 96.0+ bytes


In [26]:
df.head()

Column1  Column2  Column3
Row1        1      NaN        2
Row2        1      3.0        4
Row3        5      4.0        3

In [27]:
## Value Counts in series
df['Column1'].value_counts()

1    2
5    1
Name: Column1, dtype: int64

In [28]:
df['Column1'].unique()

array([1, 5])

In [29]:
df['Column1'].nunique()

2

In [30]:
df = pd.DataFrame({'A': [1, 2, 3], 'B': [1, 1, 1]})

In [31]:
df

A  B
0  1  1
1  2  1
2  3  1

In [32]:
df['B'].unique()

array([1])

In [33]:
df.nunique(axis=1)

0    1
1    2
2    2
dtype: int64

In [34]:
## create a DataFrame
df=pd.DataFrame(data=np.arange(0,20).reshape(5,4),index=["Row1","Row2","Row3","Row4","Row5"],
             columns=["Column1","Column2","Column3","Column4"])

In [35]:
df.head()

Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19

In [36]:
df[df['Column2']>5]

Column1  Column2  Column3  Column4
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19

In [37]:
df[df.isnull()]

Column1  Column2  Column3  Column4
Row1      NaN      NaN      NaN      NaN
Row2      NaN      NaN      NaN      NaN
Row3      NaN      NaN      NaN      NaN
Row4      NaN      NaN      NaN      NaN
Row5      NaN      NaN      NaN      NaN

In [38]:
df.head()

Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19

In [39]:
df.to_csv('test.csv',index=False)

In [40]:
df1=pd.read_csv('test.csv')
df1

Column1  Column2  Column3  Column4
0        0        1        2        3
1        4        5        6        7
2        8        9       10       11
3       12       13       14       15
4       16       17       18       19

In [41]:
df.to_excel('test.xlsx')

In [42]:
pd.read_excel('test.xlsx')

Unnamed: 0  Column1  Column2  Column3  Column4
0       Row1        0        1        2        3
1       Row2        4        5        6        7
2       Row3        8        9       10       11
3       Row4       12       13       14       15
4       Row5       16       17       18       19

In [43]:
pd.read_csv('https://download.bls.gov/pub/time.series/cu/cu.item',sep='\t')

HTTPError: ignored

In [64]:
data='{"employee_name":"Navya","email":"navya@gmail.com","job_profile":[{"title":"ML engineer","role":"Developer"}]}'

In [65]:
type(data)

str

In [66]:
df2=pd.read_json(data)

In [67]:
df2

employee_name            email  \
0         Navya  navya@gmail.com   

                                     job_profile  
0  {'title': 'ML engineer', 'role': 'Developer'}

In [68]:
df2['Salary']=100

In [69]:
df2

employee_name            email  \
0         Navya  navya@gmail.com   

                                     job_profile  Salary  
0  {'title': 'ML engineer', 'role': 'Developer'}     100

In [70]:
dict(df2['job_profile'])[0]['role']

'Developer'

In [71]:
data

'{"employee_name":"Navya","email":"navya@gmail.com","job_profile":[{"title":"ML engineer","role":"Developer"}]}'

In [72]:
pd.read_json(data,orient='records')

employee_name            email  \
0         Navya  navya@gmail.com   

                                     job_profile  
0  {'title': 'ML engineer', 'role': 'Developer'}

In [73]:
pd.read_json(data,orient='index')

0
employee_name                                            Navya
email                                          navya@gmail.com
job_profile    [{'title': 'ML engineer', 'role': 'Developer'}]

In [74]:
pd.read_json(data,orient='columns')

employee_name            email  \
0         Navya  navya@gmail.com   

                                     job_profile  
0  {'title': 'ML engineer', 'role': 'Developer'}

In [75]:
import pandas as pd
df = pd.DataFrame([['a', 'b'], ['c', 'd']],
                  index=['row 1', 'row 2'],
                  columns=['col 1', 'col 2'])

In [76]:
df

col 1 col 2
row 1     a     b
row 2     c     d

In [77]:
df.to_json()

'{"col 1":{"row 1":"a","row 2":"c"},"col 2":{"row 1":"b","row 2":"d"}}'

In [78]:
df.to_json(orient="records")

'[{"col 1":"a","col 2":"b"},{"col 1":"c","col 2":"d"}]'

In [79]:
df.to_json(orient="columns")

'{"col 1":{"row 1":"a","row 2":"c"},"col 2":{"row 1":"b","row 2":"d"}}'

In [80]:
pd.read_csv("https://archive.ics.uci.edu/ml/machine-learning-databases/wine/wine.data")

1  14.23  1.71  2.43  15.6  127   2.8  3.06   .28  2.29   5.64  1.04  \
0    1  13.20  1.78  2.14  11.2  100  2.65  2.76  0.26  1.28   4.38  1.05   
1    1  13.16  2.36  2.67  18.6  101  2.80  3.24  0.30  2.81   5.68  1.03   
2    1  14.37  1.95  2.50  16.8  113  3.85  3.49  0.24  2.18   7.80  0.86   
3    1  13.24  2.59  2.87  21.0  118  2.80  2.69  0.39  1.82   4.32  1.04   
4    1  14.20  1.76  2.45  15.2  112  3.27  3.39  0.34  1.97   6.75  1.05   
..  ..    ...   ...   ...   ...  ...   ...   ...   ...   ...    ...   ...   
172  3  13.71  5.65  2.45  20.5   95  1.68  0.61  0.52  1.06   7.70  0.64   
173  3  13.40  3.91  2.48  23.0  102  1.80  0.75  0.43  1.41   7.30  0.70   
174  3  13.27  4.28  2.26  20.0  120  1.59  0.69  0.43  1.35  10.20  0.59   
175  3  13.17  2.59  2.37  20.0  120  1.65  0.68  0.53  1.46   9.30  0.60   
176  3  14.13  4.10  2.74  24.5   96  2.05  0.76  0.56  1.35   9.20  0.61   

     3.92  1065  
0    3.40  1050  
1    3.17  1185  
2    3.45  1480  
3    2.93   735  
4    2.85  1450  
..    ...   ...  
172  1.74   740  
173  1.56   750  
174  1.56   835  
175  1.62   840  
176  1.60   560  

[177 rows x 14 columns]

In [81]:
df=pd.read_csv("https://archive.ics.uci.edu/ml/machine-learning-databases/wine/wine.data",header=None)

In [82]:
df.to_json(orient="index")

'{"0":{"0":1,"1":14.23,"2":1.71,"3":2.43,"4":15.6,"5":127,"6":2.8,"7":3.06,"8":0.28,"9":2.29,"10":5.64,"11":1.04,"12":3.92,"13":1065},"1":{"0":1,"1":13.2,"2":1.78,"3":2.14,"4":11.2,"5":100,"6":2.65,"7":2.76,"8":0.26,"9":1.28,"10":4.38,"11":1.05,"12":3.4,"13":1050},"2":{"0":1,"1":13.16,"2":2.36,"3":2.67,"4":18.6,"5":101,"6":2.8,"7":3.24,"8":0.3,"9":2.81,"10":5.68,"11":1.03,"12":3.17,"13":1185},"3":{"0":1,"1":14.37,"2":1.95,"3":2.5,"4":16.8,"5":113,"6":3.85,"7":3.49,"8":0.24,"9":2.18,"10":7.8,"11":0.86,"12":3.45,"13":1480},"4":{"0":1,"1":13.24,"2":2.59,"3":2.87,"4":21.0,"5":118,"6":2.8,"7":2.69,"8":0.39,"9":1.82,"10":4.32,"11":1.04,"12":2.93,"13":735},"5":{"0":1,"1":14.2,"2":1.76,"3":2.45,"4":15.2,"5":112,"6":3.27,"7":3.39,"8":0.34,"9":1.97,"10":6.75,"11":1.05,"12":2.85,"13":1450},"6":{"0":1,"1":14.39,"2":1.87,"3":2.45,"4":14.6,"5":96,"6":2.5,"7":2.52,"8":0.3,"9":1.98,"10":5.25,"11":1.02,"12":3.58,"13":1290},"7":{"0":1,"1":14.06,"2":2.15,"3":2.61,"4":17.6,"5":121,"6":2.6,"7":2.51,"8":0.3